

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build Seconsd
- stage: DevDeploy
  jobs:
  - job: DevDeploy
    steps:
    - bash: echo DevDeployJob
    cancelTimeoutInMinutes: 
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeploy
